const path = require('path');
const fs = require('fs-extra');

// Detect if running on Termux (Sharp WASM has issues on ARM)
const isTermux = process.env.PREFIX?.includes('com.termux') ||
    fs.existsSync('/data/data/com.termux/files/usr/bin/bash');

// Image processing library selection
// Sharp: Fast but has WASM issues on Termux
// Jimp: Pure JavaScript, works everywhere including Termux
let sharp = null;
let Jimp = null;

if (isTermux) {
    // Use Jimp on Termux (pure JavaScript, no WASM issues)
    try {
        Jimp = require('jimp');
        console.log('📱 Running on Termux - Using Jimp for custom icons');
    } catch (e) {
        console.warn('⚠️ Jimp not available. Run: npm install jimp');
    }
} else {
    // Use Sharp on other platforms (faster)
    try {
        sharp = require('sharp');
    } catch (e) {
        // Fallback to Jimp if Sharp fails
        try {
            Jimp = require('jimp');
            console.log('Using Jimp as fallback for image processing');
        } catch (e2) {
            console.warn('⚠️ No image processing library available. Custom icons disabled.');
        }
    }
}

/**
 * Generate Android project from template
 * @param {string} outputDir - Output directory
 * @param {Object} config - User configuration
 */
async function generateProject(outputDir, config) {
    const templateDir = path.join(__dirname, '..', '..', 'android-template');

    // Check if template exists
    if (!await fs.pathExists(templateDir)) {
        throw new Error('Template Android tidak ditemukan. Jalankan setup terlebih dahulu.');
    }

    // Copy template to output directory
    await fs.copy(templateDir, outputDir);

    // Generate unique package name
    const packageName = generatePackageName(config.appName);

    // Update configurations
    await updateAppName(outputDir, config.appName);
    await updateWebViewUrl(outputDir, config.url);  // Simple encoding, no encryption needed
    await updateThemeColor(outputDir, config.themeColor);

    // Update icon if provided
    if (config.iconPath && await fs.pathExists(config.iconPath)) {
        await updateAppIcon(outputDir, config.iconPath);
    }

    // Update package name in project files
    await updatePackageName(outputDir, packageName);

    // Configure AAPT2 for Termux (ARM devices need custom aapt2)
    await configureAapt2(outputDir);

    // Create local.properties with SDK path
    await createLocalProperties(outputDir);
}

/**
 * Create local.properties with SDK path
 * This is needed because PM2 doesn't read environment variables from .bashrc
 */
async function createLocalProperties(projectDir) {
    const localPropsPath = path.join(projectDir, 'local.properties');

    // Common SDK locations - check these FIRST (more reliable than env vars)
    const possiblePaths = [
        '/opt/android-sdk',                           // VPS setup script (most common)
        '/usr/lib/android-sdk',                       // apt install
        '/root/android-sdk',                          // Root user Termux
        process.env.HOME + '/android-sdk',            // Termux home
        process.env.HOME + '/Android/Sdk',            // Linux default
        'C:\\Users\\' + (process.env.USERNAME || 'User') + '\\AppData\\Local\\Android\\Sdk', // Windows
    ];

    let sdkPath = null;

    // First, check if actual SDK directories exist
    for (const p of possiblePaths) {
        if (await fs.pathExists(p)) {
            sdkPath = p;
            break;
        }
    }

    // Fallback to env vars only if no directory found
    if (!sdkPath) {
        const envPath = process.env.ANDROID_HOME || process.env.ANDROID_SDK_ROOT;
        if (envPath && await fs.pathExists(envPath)) {
            sdkPath = envPath;
        }
    }

    if (sdkPath) {
        // Normalize path for properties file (use forward slashes)
        const normalizedPath = sdkPath.replace(/\\/g, '/');
        const content = `# Auto-generated by Web2APK\nsdk.dir=${normalizedPath}\n`;
        await fs.writeFile(localPropsPath, content);
        console.log(`Created local.properties with SDK path: ${sdkPath}`);
    } else {
        console.warn('Warning: Could not find Android SDK path');
    }
}

/**
 * Configure AAPT2 path based on platform
 * - Termux: Uses system aapt2 (ARM native)
 * - Linux/VPS: Uses Maven aapt2 (default, no config needed)
 */
async function configureAapt2(projectDir) {
    const gradlePropsPath = path.join(projectDir, 'gradle.properties');

    // Check if running on Termux
    const isTermux = await fs.pathExists('/data/data/com.termux/files/usr/bin/bash');

    if (isTermux) {
        // Termux needs custom AAPT2 for ARM compatibility
        const aapt2Path = '/data/data/com.termux/files/usr/bin/aapt2';
        if (await fs.pathExists(aapt2Path)) {
            let props = await fs.readFile(gradlePropsPath, 'utf8');
            props += `\n# Termux ARM AAPT2\nandroid.aapt2FromMavenOverride=${aapt2Path}\n`;
            await fs.writeFile(gradlePropsPath, props);
            console.log('Configured AAPT2 for Termux');
        }
    }
    // For Linux/VPS: Gradle will automatically download aapt2 from Maven
}

/**
 * Update app name in strings.xml
 */
async function updateAppName(projectDir, appName) {
    const stringsPath = path.join(projectDir, 'app', 'src', 'main', 'res', 'values', 'strings.xml');

    let content = await fs.readFile(stringsPath, 'utf8');
    content = content.replace(
        /<string name="app_name">.*<\/string>/,
        `<string name="app_name">${escapeXml(appName)}</string>`
    );
    await fs.writeFile(stringsPath, content);
}

/**
 * Update WebView URL in MainActivity (with simple encoding)
 * Uses reverse + Base64 for lightweight obfuscation
 */
async function updateWebViewUrl(projectDir, url) {
    const mainActivityPath = path.join(projectDir, 'app', 'src', 'main', 'java', 'com', 'web2apk', 'app', 'MainActivity.java');

    // Simple encoding: reverse string then Base64
    const reversed = url.split('').reverse().join('');
    const encoded = Buffer.from(reversed, 'utf8').toString('base64');

    let content = await fs.readFile(mainActivityPath, 'utf8');

    // Replace ENCODED_URL
    content = content.replace(
        /private static final String ENCODED_URL = "[^"]*";/,
        `private static final String ENCODED_URL = "${encoded}";`
    );

    // Replace FALLBACK_URL with actual URL (for safety)
    content = content.replace(
        /private static final String FALLBACK_URL = "[^"]*";/,
        `private static final String FALLBACK_URL = "${url}";`
    );

    await fs.writeFile(mainActivityPath, content);
}

// Note: Complex encryption removed for performance
// The URL is now simply reversed and Base64 encoded
// This prevents casual inspection while being extremely fast to decode

/**
 * Update theme color in colors.xml
 */
async function updateThemeColor(projectDir, themeColor) {
    const colorsPath = path.join(projectDir, 'app', 'src', 'main', 'res', 'values', 'colors.xml');

    // Calculate darker variant for status bar
    const darkColor = darkenColor(themeColor, 20);

    let content = await fs.readFile(colorsPath, 'utf8');
    content = content.replace(
        /<color name="colorPrimary">.*<\/color>/,
        `<color name="colorPrimary">${themeColor}</color>`
    );
    content = content.replace(
        /<color name="colorPrimaryDark">.*<\/color>/,
        `<color name="colorPrimaryDark">${darkColor}</color>`
    );
    content = content.replace(
        /<color name="colorAccent">.*<\/color>/,
        `<color name="colorAccent">${themeColor}</color>`
    );
    await fs.writeFile(colorsPath, content);
}

/**
 * Update app icon with user's image
 * Uses Sharp on desktop/server, Jimp on Termux
 */
async function updateAppIcon(projectDir, iconPath) {
    // Check if any image library is available
    if (!sharp && !Jimp) {
        console.warn('⚠️ No image library available, using default icon');
        return;
    }

    try {
        const sizes = [
            { name: 'mipmap-mdpi', size: 48 },
            { name: 'mipmap-hdpi', size: 72 },
            { name: 'mipmap-xhdpi', size: 96 },
            { name: 'mipmap-xxhdpi', size: 144 },
            { name: 'mipmap-xxxhdpi', size: 192 }
        ];

        for (const { name, size } of sizes) {
            const outputPath = path.join(projectDir, 'app', 'src', 'main', 'res', name, 'ic_launcher.png');
            const roundOutputPath = path.join(projectDir, 'app', 'src', 'main', 'res', name, 'ic_launcher_round.png');

            // Ensure directory exists
            await fs.ensureDir(path.dirname(outputPath));

            if (sharp) {
                // Use Sharp (faster, but doesn't work on Termux)
                await sharp(iconPath)
                    .resize(size, size, { fit: 'cover' })
                    .png()
                    .toFile(outputPath);
            } else if (Jimp) {
                // Use Jimp (pure JavaScript, works on Termux)
                const image = await Jimp.read(iconPath);
                await image
                    .cover(size, size)
                    .writeAsync(outputPath);
            }

            // Copy as round icon (same as square for simplicity)
            await fs.copy(outputPath, roundOutputPath);
        }

        console.log('✅ Custom icon applied successfully');
    } catch (error) {
        console.warn('⚠️ Custom icon processing failed, using default icon:', error.message);
    }
}

/**
 * Update package name
 */
async function updatePackageName(projectDir, newPackageName) {
    // Update build.gradle - both applicationId and namespace
    const buildGradlePath = path.join(projectDir, 'app', 'build.gradle');
    let buildGradle = await fs.readFile(buildGradlePath, 'utf8');

    // Update applicationId
    buildGradle = buildGradle.replace(
        /applicationId ".*"/,
        `applicationId "${newPackageName}"`
    );

    // Update namespace (required for AGP 8.x)
    buildGradle = buildGradle.replace(
        /namespace '.*'/,
        `namespace '${newPackageName}'`
    );

    await fs.writeFile(buildGradlePath, buildGradle);

    // Note: In AGP 8.x, package attribute in AndroidManifest.xml is no longer supported
    // Namespace is now defined in build.gradle only

    // Update Java files package declaration
    const javaDir = path.join(projectDir, 'app', 'src', 'main', 'java', 'com', 'web2apk', 'app');
    const javaFiles = await fs.readdir(javaDir);

    for (const file of javaFiles) {
        if (file.endsWith('.java')) {
            const filePath = path.join(javaDir, file);
            let content = await fs.readFile(filePath, 'utf8');
            content = content.replace(
                /package com\.web2apk\.app;/,
                `package ${newPackageName};`
            );
            await fs.writeFile(filePath, content);
        }
    }
}

/**
 * Generate unique package name from app name
 */
function generatePackageName(appName) {
    const sanitized = appName
        .toLowerCase()
        .replace(/[^a-z0-9]/g, '')
        .substring(0, 20);

    const timestamp = Date.now().toString(36);
    return `com.web2apk.${sanitized || 'app'}_${timestamp}`;
}

/**
 * Escape XML special characters
 */
function escapeXml(str) {
    return str
        .replace(/&/g, '&amp;')
        .replace(/</g, '&lt;')
        .replace(/>/g, '&gt;')
        .replace(/"/g, '&quot;')
        .replace(/'/g, '&apos;');
}

/**
 * Darken a hex color
 */
function darkenColor(hex, percent) {
    const num = parseInt(hex.replace('#', ''), 16);
    const amt = Math.round(2.55 * percent);
    const R = Math.max((num >> 16) - amt, 0);
    const G = Math.max((num >> 8 & 0x00FF) - amt, 0);
    const B = Math.max((num & 0x0000FF) - amt, 0);
    return '#' + (0x1000000 + R * 0x10000 + G * 0x100 + B).toString(16).slice(1);
}

module.exports = { generateProject };
